//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2021 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

let base = """
//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2021 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

// This was auto-generated by utils/gen-unicode-data/gen-binary-props, please
// do not edit this file yourself.

#include "swift/Runtime/Debug.h"
#include "../SwiftShims/UnicodeProperties.h"


"""

func emitBinaryProperties() {
  let data = generateBinaryProperties()

  var result = base

  emitDataArray(with: data.0, into: &result)

  emitRangeIndexArray(with: data.1, data: data.0, into: &result)

  emitSoloIndexArray(with: data.2, data: data.0, into: &result)

  FileManager.default.createFile(
    atPath: "UnicodeProperties.cpp",
    contents: result.data(using: .utf8)
  )
}

func emitDataArray(with data: [ScalarBinaryProps], into str: inout String) {
  str += """
  static __swift_uint64_t _swift_stdlib_unicode_binProps_data[\(data.count)] = {

  """

  for binProp in  data {
    str += """
      \(binProp.rawValue),

    """
  }

  str += """
  };


  """
}

func emitRangeIndexArray(
  with rangeBinProps: [ScalarBinaryProps: [ClosedRange<UInt32>]],
  data: [ScalarBinaryProps],
  into str: inout String
) {
  var totalRanges = 0

  for (_, ranges) in rangeBinProps {
    totalRanges += ranges.count
  }

  str += """
  static __swift_uint64_t _swift_stdlib_unicode_binProps_index1[\(totalRanges)] = {

  """

  var rangeValues: [ClosedRange<UInt32>: UInt64] = [:]

  for (i, binProp) in data.enumerated() {
    guard let ranges = rangeBinProps[binProp] else {
      continue
    }

    for range in ranges {
      let lower = UInt64((UInt32(i) << 21) | range.lowerBound)
      let upper = UInt64((UInt32(i) << 21) | range.upperBound)

      // Our value is both lower and upper bounds in a single 64 bit integer.
      // We've packed the index into the data array in both lower and upper.
      let value = (upper << 32) | lower

      rangeValues[range] = value
    }
  }

  let sortedRangeKeys = rangeValues.keys.sorted { $0.lowerBound < $1.lowerBound }

  for range in sortedRangeKeys {
    let value = rangeValues[range]!

    str += """
      \(value),

    """
  }

  str += """
  };


  """
}

func emitSoloIndexArray(
  with soloBinProps: [ScalarBinaryProps: [UInt32]],
  data: [ScalarBinaryProps],
  into str: inout String
) {
  var totalSoloScalars = 0

  for (_, scalars) in soloBinProps {
    totalSoloScalars += scalars.count
  }

  str += """
  static __swift_uint32_t _swift_stdlib_unicode_binProps_index2[\(totalSoloScalars)] = {

  """

  var soloValues: [UInt32: UInt32] = [:]

  for (i, binProp) in data.enumerated() {
    guard let scalars = soloBinProps[binProp] else {
      continue
    }

    for scalar in scalars {
      // Our value is the scalar in the low 21 bits and the index into the data
      // array right after it for 8 bits. This leaves us with 3 bits for
      // whatever we want in the future.
      let value = (UInt32(i) << 21) | scalar

      soloValues[scalar] = value
    }
  }

  let sortedSoloKeys = soloValues.keys.sorted { $0 < $1 }

  for solo in sortedSoloKeys {
    let value = soloValues[solo]!

    str += """
      \(value),

    """
  }

  str += """
  };


  """
}

func generateBinaryProperties() -> (
  /*  */ [ScalarBinaryProps],
  [ScalarBinaryProps: [ClosedRange<UInt32>]],
  [ScalarBinaryProps: [UInt32]]
) {
  // First, let's gather the unique bin prop combinations.
  var scalarBinaryProperties: [ScalarBinaryProps: [Unicode.Scalar]] = [:]

  // Loop the entire Unicode codepoint area.
  for i in 0x0 ... 0x10FFFF {
    // These codepoints aren't used (0xD800 ... 0xDFFF).
    guard let scalar = Unicode.Scalar(i) else {
      continue
    }

    let binaryProps = getScalarBinaryProps(for: scalar)

    scalarBinaryProperties[binaryProps, default: []].append(scalar)
  }

  // Flatten the scalar array by using closed ranges to represent massive
  // amounts of scalars.
  var binaryPropRanges: [ScalarBinaryProps: [ClosedRange<UInt32>]] = [:]

  // Also keep track of singular scalars who have a particular binary property
  // representation to save space in the eventual index array.
  var binaryPropsSolo: [ScalarBinaryProps: [UInt32]] = [:]

  for (binaryProps, scalars) in scalarBinaryProperties {
    var lower = scalars.first!
    var upper = scalars.first!

    for scalar in scalars {
      // Only occurs for the first element.
      if scalar == upper {
        continue
      }

      // If the next scalar is a step up in the current range, increase it.
      if scalar.value == upper.value + 1 {
        upper = scalar
      } else {
        // Otherwise, we've reached a new range.

        // If our range is only a single scalar, put it in the solo dict.
        if lower == upper {
          binaryPropsSolo[
            binaryProps, default: []
          ].append(lower.value)
        } else {
          binaryPropRanges[
            binaryProps, default: []
          ].append(lower.value ... upper.value)
        }

        lower = scalar
        upper = scalar
      }
    }
    
    // If our range is only a single scalar, put it in the solo dict.
    if lower == upper {
      binaryPropsSolo[
        binaryProps, default: []
      ].append(lower.value)
    } else {
      binaryPropRanges[
        binaryProps, default: []
      ].append(lower.value ... upper.value)
    }
  }

  return (Array(scalarBinaryProperties.keys), binaryPropRanges, binaryPropsSolo)
}

emitBinaryProperties()
